### ISSUE TITLE
[bug]: Signed URLs (for example from AWS S3) are unable to be played

### ISSUE THREAD

**Issue by jballentine-sharpen** [asterisk/asterisk#463]
### Severity

Trivial

### Versions

16

### Components/Modules

ARI, Playback

### Operating Environment

Linux, irrelevant

### Frequency of Occurrence

Constant

### Issue Description

When using a signed URL with a Playback, playing the sound does not work. This is because of the way the Asterisk code checks for the file extension in the URL (I verified this ~a year ago by searching through the source code. I don't have time to do that again, but I am instead just reporting this issue finally).

From what I remember, it splits the URL by `.` and takes the last element of the resulting array. This might be fine when the URL ends with the file name + extension, but when the URL ends with query params for authorizing the file, and those query params contain periods, then it does not work. Even if it didn't contain periods, I'm betting it would include the entire query params along with the extension, which still wouldn't work.

The way we've gotten around this at my company is by adding `&ext=.wav` to the end of our signed URLs. This tricks Asterisk into reading the extension correctly and luckily does not affect the signed URL at all.

The easy fix for this of course is to throw away the query params of the URL before parsing it. 

Hopefully this all makes sense. We spent a lot of time in the past trying to figure out why signed URLs don't work on their own, so I would hope that this could get fixed to help anybody else encountering this.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
Has this not already been fixed by https://github.com/asterisk/asterisk/commit/68dbcd5ef5de3be4743bb107055a19ea01a7e074 ?

**Comment by jcolp** [comment]
With this being the legacy issue: http://issues-archive.asterisk.org/ASTERISK-27871

**Comment by jballentine-sharpen** [comment]
Well, all the more reason for us to upgrade asterisk version....

Thanks for the fast response, and my bad for not digging into this more deeply to confirm it was still an issue before posting. I did do some issue searching but I did not see any relevant results.

Glad to see it's fixed and something to look forward to after upgrading :)
